name: release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Git set user
        run: |
          git config --local user.email "WilliamChelman@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      # Dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-cache-${{ hashFiles('./package-lock.json') }}
      - name: Install root dependencies
        run: npm i
      # Build and release
      - name: Building
        run: npm run build-all
      - name: Testing
        run: npm t
      - name: Releasing
        run: npm run release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
